### ISSUE TITLE
Pip version outdated

### ISSUE THREAD

**Issue by guumaster** [mgaitan/radiocut_downloader#12]
After installing this library with `pip3 install radiocut_downloader`  I've got a version that doesn't support radiostation urls. 

I've checked the installed code and `master` branch, and I'm getting an older version. You can see the diff [here](https://github.com/mgaitan/radiocut_downloader/commit/2c14c851f31a4ef7bd64997d38aa5bc3237ebb07#diff-f62caeb0301241add4b612f4127fd680) (you get the left version after installation instead of the latest from `master`).

Can you publish a new version to `PyPI`?

**Comment by mgaitan** [comment]
I've just uploaded a new one. please let me know if it works ok.

**Comment by guumaster** [comment]
It works. Thanks!
