### ISSUE TITLE
no longer works, error "ValueError: could not convert string to float"

### ISSUE THREAD

**Issue by fcassia2017** [mgaitan/radiocut_downloader#3]
Sample URL to reproduce
radiocut http://radiocut.fm/radiostation/metro951/listen/2016/09/30/18/00/00

Desired outcome: script works

What happens:
$ radiocut http://radiocut.fm/radiostation/metro951/listen/2016/09/30/18/00/00
Retrieving http://radiocut.fm/radiostation/metro951/listen/2016/09/30/18/00/00
Getting chunks index http://chunkserver.radiocut.fm/server/get_chunks/metro951/147526/
Traceback (most recent call last):
  File "/usr/local/bin/radiocut", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/radiocut/**init**.py", line 81, in main
    radiocut(arguments['<audiocut_url>'], arguments['<output-file-name>'])
  File "/usr/local/lib/python2.7/dist-packages/radiocut/**init**.py", line 41, in radiocut
    if c['start'] + c['length'] > float(seconds) + float(duration):
ValueError: could not convert string to float: 
nando@ZBOXNANO-AD12 ~/Downloads $

**Comment by mgaitan** [comment]
Hola, estás probando con una URL a un segundo en particular de la estación, no a un "recorte". 

probá por ejemplo 

```
radiocut http://radiocut.fm/audiocut/matias-martin-y-el-cinismo-del-discurso-de-macri/
```

Confirmame si es eso, 

de paso, si te animás, aceptaría gustoso un PR para que falle con una explicación más clara para el usuario cuando se da una url que no es un "audiocut" (basicamente verificar que el argumento empieza con `http://radiocut.fm/audiocut/`)

**Comment by fcassia2017** [comment]
Hola,

Yo antes he usado la sintaxis del bug report para bajar un programa completo y funcionaba...
Ahora que veo que actualizaste el código probaré nuevamente...
FC

**Comment by fcassia2017** [comment]
Veo que no, si quiero bajar un programa entero de una fecha determinada tengo que crear un nuevo corte con la duracion completa.

**Comment by fcassia2017** [comment]
No estoy acostumbrado a Github me gusta mas Bugzilla, pero son preferencias... 
por lo menos en Bugzilla se puede convertir un bug en un RFE (Request for Enhancement).

En este caso el feature request seria que cuando le pasas como parámetro en vez de un corte ya hecho una posición, que vaya bajando hasta que el programa cambia de nombre (si vas clickeando con la GUI en algun momento vez que determinado time setting corresponde a otro programa, IF so = end). Claro que no tengo idea de que tan complicado es eso desde el código, aunque ví que RadioCut corta las grabaciones en mini-segmentos...
